const nx = require('@nx/eslint-plugin')
const { FlatCompat } = require('@eslint/eslintrc')
const globals = require('globals')

// eslint-config-next 15 only ships the legacy format, so it goes through FlatCompat
// (https://nextjs.org/docs/15/app/api-reference/config/eslint).
const compat = new FlatCompat({ baseDirectory: __dirname })

module.exports = [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '.nx/**',
      // Generated by `npm run generate-api-client`. Edits get overwritten, so lint findings there are noise.
      'apps/web/src/api/**',
    ],
  },

  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],

  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [],
          depConstraints: [{ sourceTag: '*', onlyDependOnLibsWithTags: ['*'] }],
        },
      ],
    },
  },

  // These two need type information, so they only run on source covered by a tsconfig.
  {
    // Globs stay project-relative so libs/shared/eslint.config.cjs can reuse this block.
    files: ['**/src/**/*.ts', '**/src/**/*.tsx'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },

  // Web app (Next.js). Next's config goes last among the web blocks, as its docs ask.
  ...nx.configs['flat/react-typescript'].map(config => ({
    ...config,
    files: ['apps/web/**/*.ts', 'apps/web/**/*.tsx'],
  })),
  ...compat
    .config({
      extends: ['next', 'next/core-web-vitals'],
      settings: { next: { rootDir: 'apps/web/' } },
    })
    .map(config => ({ ...config, files: ['apps/web/**/*.{js,jsx,ts,tsx}'] })),
  {
    files: ['apps/web/**/*.{js,jsx,ts,tsx}'],
    rules: {
      // App Router only. This rule checks links against a pages/ directory, which doesn't exist here.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },

  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/*.spec.js', '**/*.spec.jsx'],
    languageOptions: {
      globals: globals.jest,
    },
  },
]
