const nx = require('@nx/eslint-plugin')
const nextVitals = require('eslint-config-next/core-web-vitals')
const globals = require('globals')

module.exports = [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '.nx/**',
      // Generated by `npm run generate-api-client`. Edits get overwritten, so lint findings there are noise.
      'apps/web/src/api/**',
    ],
  },

  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],

  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // DTO properties need their explicit type: decorator metadata (Swagger, class-validator) is only
      // emitted from annotations, so `active = false` would be described as Object instead of Boolean.
      '@typescript-eslint/no-inferrable-types': ['error', { ignoreProperties: true }],
    },
  },

  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [],
          depConstraints: [{ sourceTag: '*', onlyDependOnLibsWithTags: ['*'] }],
        },
      ],
    },
  },

  // These two need type information, so they only run on source covered by a tsconfig.
  {
    // Globs stay project-relative so libs/shared/eslint.config.cjs can reuse this block.
    files: ['**/src/**/*.ts', '**/src/**/*.tsx'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },

  // Web app (Next.js). Next's config goes last among the web blocks, as its docs ask.
  ...nx.configs['flat/react-typescript'].map(config => ({
    ...config,
    files: ['apps/web/**/*.ts', 'apps/web/**/*.tsx'],
  })),
  // eslint-config-next 16 ships flat config (https://nextjs.org/docs/app/api-reference/config/eslint).
  // Its ignores-only entry stays global; everything else is scoped to the web app.
  ...nextVitals.map(config =>
    config.ignores
      ? config
      : {
          ...config,
          files: ['apps/web/**/*.{js,jsx,ts,tsx}'],
          settings: { ...config.settings, next: { rootDir: 'apps/web/' } },
        },
  ),
  {
    files: ['apps/web/**/*.{js,jsx,ts,tsx}'],
    rules: {
      // App Router only. This rule checks links against a pages/ directory, which doesn't exist here.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },

  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/*.spec.js', '**/*.spec.jsx'],
    languageOptions: {
      globals: globals.jest,
    },
  },
]
