export enum ConfigEnum {
  JwtAccessTokenSecret = 'JWT_ACCESS_TOKEN_SECRET',
  JwtAccessTokenExpirationTime = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JwtAccessTokenAudience = 'JWT_ACCESS_TOKEN_AUDIENCE',
  JwtVerificationTokenSecret = 'JWT_VERIFICATION_TOKEN_SECRET',
  JwtVerificationTokenExpirationTime = 'JWT_VERIFICATION_TOKEN_EXPIRATION_TIME',
  ResendApiKey = 'RESEND_API_KEY',
  EmailResetPasswordUrl = 'EMAIL_RESET_PASSWORD_URL',
  MongoUri = 'MONGO_URI',
  PaypalClientId = 'PAYPAL_CLIENT_ID',
  PaypalClientSecret = 'PAYPAL_CLIENT_SECRET',
  PaypalEnvironment = 'PAYPAL_ENVIRONMENT',
  SupabaseUrl = 'SUPABASE_URL',
  SupabaseServiceRoleKey = 'SUPABASE_SERVICE_ROLE_KEY',
  TurnstileSecretKey = 'TURNSTILE_SECRET_KEY',
}
